import { Platform } from "react-native";
import { ScaledSheet } from "react-native-size-matters";
import { COLOURS } from "../colours";

const scoring = ScaledSheet.create({
  addButtonContainer: {
    marginHorizontal: "10@s",
    marginBottom: "5@s",
    marginTop: "10@s",
    flex: 1,
    backgroundColor: COLOURS.black,
    opacity: 0.95,
    position: "relative",
    height: "100%",
    borderRadius: 5,
  },
  bagRow: {
    paddingTop: 0,
    justifyContent: "center",
    flexDirection: "row",
    alignContent: "space-around",
  },
  bagRowLand: {
    paddingTop: 0,
    flexDirection: "row",
    alignContent: "space-between",
  },
  bagRowButton: {
    width: "48@s",
    height: "48@s",
    borderWidth: 1,
    borderColor: COLOURS.mediumGrey,
    backgroundColor: COLOURS.black,
    borderRadius: "6@s",
    marginVertical: "6@vs",
    marginHorizontal: "5@s",
  },
  bagRowButtonLand: {
    width: "44@s",
    height: "44@s",
    borderWidth: 1,
    borderColor: COLOURS.mediumGrey,
    backgroundColor: COLOURS.black,
    borderRadius: "6@s",
    marginVertical: "6@vs",
    marginHorizontal: "4@s",
  },
  bagRowButtonSelected: {
    borderWidth: 2,
    borderColor: COLOURS.white,
    backgroundColor: COLOURS.black,
  },
  bagRowButtonText: {
    fontSize: Platform.OS === "android" ? "30@s" : "25@s",
    fontWeight: "bold",
    color: COLOURS.lightGrey,
    textAlign: "center",
  },
  bagRowButtonTextSelected: {
    color: COLOURS.white,
  },
  bagRowTextDisabled: {
    color: COLOURS.black,
  },
  bagRowHeading: {
    width: "60@s",
    textAlign: "center",
    fontSize: Platform.OS === "android" ? "26@s" : "21@s",
    fontWeight: "bold",
    color: COLOURS.white,
    marginTop: Platform.OS === "android" ? "8@s" : "8@s",
    marginRight: "5@s",
  },
  bagRowHeadingLand: {
    width: "50@s",
    textAlign: "center",
    fontSize: Platform.OS === "android" ? "26@s" : "21@s",
    fontWeight: "bold",
    color: COLOURS.white,
    marginTop: Platform.OS === "android" ? "8@s" : "8@s",
    marginRight: "0@s",
  },
  btnSpacer: {
    paddingHorizontal: 14,
  },
  btnSpacerLand: {
    paddingVertical: 10,
  },
  buttonRow: {
    paddingVertical: 16,
    justifyContent: "center",
    flexDirection: "row",
    alignContent: "space-between",
  },
  buttonsContainer: {
    marginTop: "0@vs",
  },
  buttonsScrollContainer: {
    marginTop: "0@vs", 
    maxHeight: "140@vs",
    overflow: "scroll",
  },
  container: {
    paddingHorizontal: 16,
    flex: 1,
    justifyContent: "flex-start",
    backgroundColor: COLOURS.appBkgColour,
  },
  containerLand: {
    paddingHorizontal: "4%",
    paddingVertical: 0,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-start",
    backgroundColor: COLOURS.appBkgColour,
  },
  containerPort: {
    paddingHorizontal: 16,
    paddingVertical: 0,
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: COLOURS.appBkgColour,
  },
  editContainerAPort: {
    height: "240@vs",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    marginTop: 10,
    backgroundColor: COLOURS.primaryTheme,
  },
  editRoundText: {
    fontSize: "14@s",
    fontWeight: "400",
    color: COLOURS.white,
    marginTop: "8@vs",
   
  },
  midButtonContainer: {
    height: "50@vs",
    paddingVertical: "7@vs",
    justifyContent: "center",
    backgroundColor: COLOURS.appBkgColour,
    flexDirection: "row",
    alignContent: "space-between",
  },
  midButtonContainerLand: {
    width: "10%",
    paddingHorizontal: "1@vs",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLOURS.appBkgColour,
    flexDirection: "column",
    marginTop: 10,
  },
  minusButtonContainer: {
    marginHorizontal: "10@s",
    marginBottom: "10@s",
    marginTop: "5@s",
    flex: 1,
    backgroundColor: COLOURS.black,
    opacity: 0.8,
    height: "100%",
    borderRadius: 5,
  },
  minusButtonContainerLand: {
    marginHorizontal: "10@s",
    marginBottom: "10@s",
    marginTop: "5@s",
    flex: 1,
    backgroundColor: COLOURS.black,
    opacity: 0.8,
    height: "100%",
    borderRadius: 5,
  },
  playerText: {
    position: "absolute",
    left: 15,
    top: 7,
    fontSize: "18@s",
    fontWeight: "600",
    color: COLOURS.white,
  },
  playerTitleOnlyContainer: {
    marginHorizontal: "10@s",
    marginBottom: "5@s",
    marginTop: "10@s",
    flex: 1,
    backgroundColor: COLOURS.black,
    opacity: 0.95,
    position: "relative",
    height: "100%",
    borderRadius: 5,
  },
  playerTitle: {
    textAlign: "center",
    fontSize: "20@s",
    fontWeight: "600",
    color: COLOURS.white,
    marginBottom: "10@vs",
  },
  QRContainer: {
    marginTop: 20,
    marginBottom: 30,
    marginHorizontal: "auto",
  },
  roundButton: {
    width: "52@s",
    height: "48@s",
    borderWidth: 2,
    borderColor: COLOURS.black,
    backgroundColor: COLOURS.black,
    borderRadius: "6@s",
    marginVertical: "6@vs",
    marginHorizontal: "3@s",
  },
  roundButtonSelected: {
    borderColor: COLOURS.green,
  },
  roundButtonText: {
    fontSize: Platform.OS === "android" ? "10@s" : "8@s",
    fontWeight: "400",
    color: COLOURS.lightGrey,
    textAlign: "center",
    marginTop: 2,
  },
  roundRow: {
    paddingTop: 0,
    justifyContent: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "space-between",
  },
  roundRowScroll: {
    paddingTop: 0,
    justifyContent: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "space-between",
  },
  roundScoreButtonText: {
    fontSize: Platform.OS === "android" ? "20@s" : "16@s",
    fontWeight: "500",
    color: COLOURS.white,
    textAlign: "center",
  },
  roundText: {
    fontSize: "14@s",
    fontWeight: "400",
    color: COLOURS.white,
    marginTop: "8@vs",
  },
  roundTextLand: {
    fontSize: "12@s",
    fontWeight: "400",
    color: COLOURS.white,
  },
  roundTitleText: {
    marginTop: "15@s",
    marginBottom: "5@s",
    color: COLOURS.white,
    textAlign: "center",
    fontSize: "18@s",
    fontWeight: "bold",
  },
  roundTitleTextLand: {
    fontSize: "18@s",
    fontWeight: "bold",
    color: COLOURS.white,
  },
  roundTextSolo: {
    position: "absolute",
    right: 15,
    bottom: 7,
    fontSize: "16@s",
    fontWeight: "400",
    color: COLOURS.white,
  },
  roundTextDisabled: {
    color: COLOURS.black,
  },
  saveButton: {
    width: "70%",
    borderWidth: 2,
    borderColor: COLOURS.white,
    backgroundColor: COLOURS.inputBkg,
    borderRadius: "6@s",
    paddingTop: "7@s",
    paddingBottom: "8@s",
    marginVertical: "2@vs",
    marginHorizontal: "auto",
  },
  saveButtonText: {
    fontSize: Platform.OS === "android" ? "20@s" : "16@s",
    fontWeight: "500",
    color: COLOURS.white,
    textAlign: "center",
  },
  scoreButtonText: {
    fontSize: 20,
    color: COLOURS.white,
    fontWeight: "bold",
    alignSelf: "center",
    textTransform: "uppercase",
    marginTop: 3,
    position: "absolute",
    opacity: 0.2,
    right: 10,
  },
  scoreButtonTextBottom: {
    bottom: 10,
  },
  scoreButtonTextTop: {
    top: 10,
  },
  scoreContainer: {
    padding: "10@s",
    height: "240@vs",
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
  },
  scoreContainerALand: {
    height: "240@vs",
    width: "43%",
    display: "flex",
    backgroundColor: COLOURS.primaryTheme,
  },
  scoreContainerAPort: {
    height: "240@vs",
    width: "100%",
    display: "flex",
    marginTop: 10,
    backgroundColor: COLOURS.primaryTheme,
  },
  scoreContainerBLand: {
    height: "240@vs",
    width: "43%",
    display: "flex",
    backgroundColor: COLOURS.mediumGrey,
  },
  scoreContainerBPort: {
    height: "240@vs",
    width: "100%",
    display: "flex",
    backgroundColor: COLOURS.mediumGrey,
  },
  scoreTitle: {
    fontSize: Platform.OS === "android" ? "150@s" : "140@s",
    fontWeight: "600",
    color: COLOURS.white,
    textAlign: "center",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  scoreTitleSmallRight: {
    fontSize: Platform.OS === "android" ? "80@s" : "70@s",
    fontWeight: "600",
    color: COLOURS.white,
    textAlign: "right",
    paddingRight: "10@s",
  },
  scoreView: {
    position: "absolute",
    width: "100%",
    height: "100%",
    justifyContent: "center",
  },
  skipButton: {
    borderWidth: 2,
    borderColor: COLOURS.mediumGrey,
    backgroundColor: COLOURS.inputBkg,
    borderRadius: "6@s",
    padding: "6@s",
    marginVertical: "2@vs",
    marginHorizontal: "5@s",
  },
  smallButton: {
    borderWidth: 1,
    borderColor: COLOURS.whiteOpaque,
    backgroundColor: COLOURS.inputBkg,
    borderRadius: "6@s",
    padding: "6@s",
    marginVertical: "2@vs",
    marginHorizontal: "5@s",
  },
  smallButtonText: {
    color: COLOURS.white,
    fontSize: "14@s",
  },
});

export default scoring;
