interface Colour {
  appBkgColour: string;
  primaryTheme: string;
  primaryOpaque: string;
  black: string;
  blackOpaque: string;
  darkGrey: string;
  mediumGrey: string;
  lightGrey: string;
  white: string;
  white2nd: string;
  whiteOpaque: string;
  blue: string;
  blue2nd: string;
  blueLogoLight: string;
  green: string;
  green2nd: string;
  greenOpaque: string;
  red: string;
  red2nd: string;
  yellow: string;
  yellow2nd: string;
  orange: string;
  orange2nd: string;
  purple: string;
  purple2nd: string;
  placeholderText: string;
  inputBkg: string;
  inputBorder: string;
  btnGreenBgk: string;
  btnBlueBgk: string;
  btnRedBgk: string;
  btnOrangeBgk: string;
  btnYellowBgk: string;
  btnPurpleBgk: string;
  btnGreenText: string;
  btnBlueText: string;
  btnRedText: string;
  btnOrangeText: string;
  btnYellowText: string;
  btnPurpleText: string;
}

export const COLOURS: Colour = {
  appBkgColour: "#171717",
  primaryTheme: "#32ADE6",
  primaryOpaque: "rgba(62, 230, 146,0.4)",
  black: "#000000",
  blackOpaque: "rgba(12,15,20,0.8)",
  darkGrey: "#191919",
  mediumGrey: "#484848",
  lightGrey: "#8F8E94",
  white: "#ffffff",
  white2nd: "#efefef",
  whiteOpaque: "rgba(255,255,255,0.4)",
  blue: "#007AFF",
  //blue: "#0062FF",
  blue2nd: "#73FBFD",
  blueLogoLight: "#32ADE6",
  //green: "#3DD598",
  green: "#75F94C",
  green2nd: "#0DA166",
  greenOpaque: "rgba(62, 230, 146, 0.4)",
  //red: "#FF575F",
  red: "#EB3223",
  red2nd: "#EB3223",
  yellow: "#FFFD54",
  yellow2nd: "#FFFD54",
  //orange: "#FFBC25",
  orange: "#FF8A34",
  orange2nd: "#FFFD54",
  purple: "#755FE2",
  purple2nd: "#AF9FFD",
  placeholderText: "#A9A9A9",
  inputBkg: "#0d0d0d",
  inputBorder: "#0d0d0d",
  btnGreenBgk: "#002404",
  btnBlueBgk: "#00102A",
  btnRedBgk: "#270300",
  btnOrangeBgk: "#251600",
  btnYellowBgk: "#242200",
  btnPurpleBgk: "#755FE2",
  btnGreenText: "#00FF1E",
  btnBlueText: "#00B2FF",
  btnRedText: "#FF3636",
  btnOrangeText: "#FF9500",
  btnYellowText: "#FFF600",
  btnPurpleText: "#ffffff",
};
